version: '3.9'
services:
  django:
    build: ghcr.io/papimarcis/web_personal:lastest
    restart: always
    ports:
      - "${DJANGO_PORT}:8080"
    command:
      - /bin/sh
      - -c
      - |
        python manage.py makemigrations
        python manage.py migrate
        python create_superuser.py
        python manage.py runserver 0.0.0.0:8080
