version: '3.9'
services:
  django:
    image: ghcr.io/papimarcis/web_personal:lastest
    restart: always
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_ALLOWED_HOST=${DJANGO_ALLOWED_HOST}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
    ports:
      - "${DJANGO_PORT}:8080"
    command:
      - /bin/sh
      - -c
      - |
        python manage.py makemigrations
        python manage.py migrate
        python create_superuser.py
        python manage.py runserver 0.0.0.0:8080
