name: publish

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  create-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Build Docker image
        run: |
          docker login --username ${{ github.actor }} --password ${{ secrets.PROD_TOKEN }} ghcr.io
          docker build . --tag ghcr.io/papimarcis/web_personal:lastest
          docker push ghcr.io/papimarcis/web_personal:lastest
